    DROP TABLE ADMIN ;
    DROP TABLE BUDDY ;
    DROP TABLE BUDDY_BOARD ;
    DROP TABLE DEAL_STATE ;
    DROP TABLE FOLLOW ;
    DROP TABLE FOLLOWING ;
    DROP TABLE GUIDE_BOARD ;
    DROP TABLE LOCATION ;
    DROP TABLE MEMBER ;
    DROP TABLE MEMBER_ATTACHMENT ;
    DROP TABLE PART_BUDDY ;
    DROP TABLE QNA ;
    DROP TABLE REPORT ;
    DROP TABLE REVIEW ;
    DROP TABLE REVIEW_ATTACHMENT ;
    DROP TABLE RPT_REASON ;
    DROP TABLE SHARE_ATTACHMENT ;
    DROP TABLE SHARE_BOARD ;
    DROP TABLE SHARE_KIND ;
    DROP TABLE TRIP_PLAN ;
    
    CREATE TABLE "MEMBER" (
        "MID"	VARCHAR2(30)		NOT NULL,
        "NICK"	VARCHAR2(30)		NOT NULL,
        "PWD"	VARCHAR2(30)		NOT NULL,
        "NAME"	VARCHAR2(30)		NOT NULL,
        "GENDER"	CHAR		NOT NULL,
        "EMAIL"	VARCHAR2(30)		NOT NULL,
        "MKIND"	NUMBER		NOT NULL,
        "FOLLOW"	NUMBER		NULL,
        "GRADE"	NUMBER		NULL,
        "STATUS"	CHAR		NOT NULL
    );
    
    COMMENT ON COLUMN "MEMBER"."MID" IS '회원아이디';
    
    COMMENT ON COLUMN "MEMBER"."NICK" IS '닉네임';
    
    COMMENT ON COLUMN "MEMBER"."PWD" IS '비밀번호';
    
    COMMENT ON COLUMN "MEMBER"."NAME" IS '이름';
    
    COMMENT ON COLUMN "MEMBER"."GENDER" IS '성별';
    
    COMMENT ON COLUMN "MEMBER"."EMAIL" IS '이메일';
    
    COMMENT ON COLUMN "MEMBER"."MKIND" IS '일반1/가이드2';
    
    COMMENT ON COLUMN "MEMBER"."FOLLOW" IS '팔로워수';
    
    COMMENT ON COLUMN "MEMBER"."GRADE" IS '평점';
    
    COMMENT ON COLUMN "MEMBER"."STATUS" IS '탈퇴여부';
    
    CREATE TABLE "ADMIN" (
        "AID"	VARCHAR2(30)		NOT NULL,
        "PWD"	VARCHAR2(30)		NOT NULL,
        "EMAIL"	VARCHAR2(30)		NOT NULL
    );
    
    COMMENT ON COLUMN "ADMIN"."AID" IS '관리자 아이디';
    
    COMMENT ON COLUMN "ADMIN"."PWD" IS '비밀번호';
    
    COMMENT ON COLUMN "ADMIN"."EMAIL" IS '이메일';
    
    CREATE TABLE "QNA" (
        "QNUM"	NUMBER		NOT NULL,
        "MID"	VARCHAR2(30)		NOT NULL,
        "CONTENT"	VARCHAR2(4000)		NOT NULL,
        "DATE"	DATE		NOT NULL,
        "ANSWER_STATUS"	CHAR		NOT NULL,
        "PUBLIC_STATUS"	CHAR		NOT NULL
    );
    
    COMMENT ON COLUMN "QNA"."QNUM" IS '게시글 번호';
    
    COMMENT ON COLUMN "QNA"."MID" IS '작성자';
    
    COMMENT ON COLUMN "QNA"."CONTENT" IS '게시글 내용';
    
    COMMENT ON COLUMN "QNA"."DATE" IS '작성날짜';
    
    COMMENT ON COLUMN "QNA"."ANSWER_STATUS" IS '답변완료여부';
    
    COMMENT ON COLUMN "QNA"."PUBLIC_STATUS" IS '게시글 공개 여부';
    
    CREATE TABLE "REVIEW" (
        "RNUM"	NUMBER		NOT NULL,
        "TITLE"	VARCHAR2(50)		NOT NULL,
        "MID"	VARCHAR2(30)		NOT NULL,
        "CONTENT"	VARCHAR2(4000)		NOT NULL,
        "DATE"	DATE		NOT NULL,
        "STATUS"	CHAR		NULL
    );
    
    COMMENT ON COLUMN "REVIEW"."RNUM" IS '게시글번호';
    
    COMMENT ON COLUMN "REVIEW"."TITLE" IS '게시글제목';
    
    COMMENT ON COLUMN "REVIEW"."MID" IS '게시글작성자';
    
    COMMENT ON COLUMN "REVIEW"."CONTENT" IS '게시글내용';
    
    COMMENT ON COLUMN "REVIEW"."DATE" IS '게시글작성일';
    
    COMMENT ON COLUMN "REVIEW"."STATUS" IS '게시글 존재여부';
    
    CREATE TABLE "REPORT" (
        "RKEY"	NUMBER		NOT NULL,
        "RMID"	VARCHAR2(30)		NOT NULL,
        "MID"	VARCHAR2(30)		NOT NULL,
        "RSNUM"	NUMBER		NOT NULL,
        "REASON"	VARCHAR2(4000)		NULL,
        "STATUS"	CHAR		NOT NULL
    );
    
    COMMENT ON COLUMN "REPORT"."RKEY" IS '신고목록번호';
    
    COMMENT ON COLUMN "REPORT"."RMID" IS '신고된회원아이디';
    
    COMMENT ON COLUMN "REPORT"."MID" IS '신고한회원아이디';
    
    COMMENT ON COLUMN "REPORT"."RSNUM" IS '신고사유항목에 대한 번호';
    
    COMMENT ON COLUMN "REPORT"."REASON" IS '신고사유 상세내용';
    
    COMMENT ON COLUMN "REPORT"."STATUS" IS '신고 처리 상태';
    
    CREATE TABLE "BUDDY" (
        "MID"	VARCHAR2(30)		NOT NULL,
        "BID"	VARCHAR2(30)		NOT NULL,
        "BNUM"	NUMBER		NOT NULL,
        "BCOUNT"	NUMBER		NOT NULL
    );
    
    COMMENT ON COLUMN "BUDDY"."MID" IS '등록회원아이디';
    
    COMMENT ON COLUMN "BUDDY"."BID" IS '동행회원 아이디';
    
    COMMENT ON COLUMN "BUDDY"."BNUM" IS '게시글 번호';
    
    COMMENT ON COLUMN "BUDDY"."BCOUNT" IS '동행 인원';
    
    CREATE TABLE "LOCATION" (
        "COUNTRY"	VARCHAR2(30)		NOT NULL,
        "CITY"	VARCHAR2(30)		NOT NULL,
        "KIND"	NUMBER		NOT NULL
    );
    
    COMMENT ON COLUMN "LOCATION"."COUNTRY" IS '여행국가';
    
    COMMENT ON COLUMN "LOCATION"."CITY" IS '여행도시';
    
    COMMENT ON COLUMN "LOCATION"."KIND" IS '국내1/해외2';
    
    CREATE TABLE "BUDDY_BOARD" (
        "BNUM"	NUMBER		NOT NULL,
        "TITLE"	VARCHAR2(50)		NOT NULL,
        "PART_YN"	CHAR		NOT NULL,
        "CONTENT"	VARCHAR2(4000)		NOT NULL,
        "DATE"	DATE		NOT NULL,
        "MID"	VARCHAR2(30)		NOT NULL,
        "COUNTRY"	VARCHAR2(30)		NOT NULL,
        "CITY"	VARCHAR2(#0)		NOT NULL,
        "START_DATE"	DATE		NOT NULL,
        "END_DATE"	DATE		NOT NULL,
        "STATUS"	CHAR		NOT NULL
    );
    
    COMMENT ON COLUMN "BUDDY_BOARD"."BNUM" IS '게시글 번호';
    
    COMMENT ON COLUMN "BUDDY_BOARD"."TITLE" IS '게시글 제목';
    
    COMMENT ON COLUMN "BUDDY_BOARD"."PART_YN" IS '동행 참여 구분';
    
    COMMENT ON COLUMN "BUDDY_BOARD"."CONTENT" IS '동행 게시글 내용';
    
    COMMENT ON COLUMN "BUDDY_BOARD"."DATE" IS '게시글 작성일';
    
    COMMENT ON COLUMN "BUDDY_BOARD"."MID" IS '회원아이디';
    
    COMMENT ON COLUMN "BUDDY_BOARD"."COUNTRY" IS '여행국가';
    
    COMMENT ON COLUMN "BUDDY_BOARD"."CITY" IS '여행도시';
    
    COMMENT ON COLUMN "BUDDY_BOARD"."START_DATE" IS '여행 출발일';
    
    COMMENT ON COLUMN "BUDDY_BOARD"."END_DATE" IS '여행종료일';
    
    COMMENT ON COLUMN "BUDDY_BOARD"."STATUS" IS '게시글 존재여부';
    
    CREATE TABLE "PART_BUDDY" (
        "MID"	VARCHAR2(30)		NOT NULL,
        "BID"	VARHAR2(30)		NOT NULL,
        "BNUM"	NUMBER		NOT NULL,
        "START_DATE"	DATE		NOT NULL,
        "END_DATE"	DATE		NOT NULL
    );
    
    COMMENT ON COLUMN "PART_BUDDY"."MID" IS '등록 회원 아이디';
    
    COMMENT ON COLUMN "PART_BUDDY"."BID" IS '동행 회원 아이디';
    
    COMMENT ON COLUMN "PART_BUDDY"."BNUM" IS '게시글 번호';
    
    COMMENT ON COLUMN "PART_BUDDY"."START_DATE" IS '여행 시작일';
    
    COMMENT ON COLUMN "PART_BUDDY"."END_DATE" IS '여행 종료일';
    
    CREATE TABLE "TRIP_PLAN" (
        "TPNUM"	NUMBER		NOT NULL,
        "TITLE"	VARCHAR2(30)		NOT NULL,
        "MID"	VARCHAR2(30)		NOT NULL,
        "DAY"	NUMBER		NOT NULL,
        "CONTENT"	VARCHAR2(4000)		NULL,
        "DATE"	DATE		NOT NULL,
        "COUNTRY"	VARCHAR2(30)		NOT NULL,
        "CITY"	VARCHAR2(30)		NOT NULL,
        "START_DATE"	DATE		NULL,
        "END_DATE"	DATE		NULL,
        "STATUS"	CHAR		NULL
    );
    
    COMMENT ON COLUMN "TRIP_PLAN"."TPNUM" IS '게시글번호';
    
    COMMENT ON COLUMN "TRIP_PLAN"."TITLE" IS '게시글제목';
    
    COMMENT ON COLUMN "TRIP_PLAN"."MID" IS '게시글작성자';
    
    COMMENT ON COLUMN "TRIP_PLAN"."DAY" IS '여행일차';
    
    COMMENT ON COLUMN "TRIP_PLAN"."CONTENT" IS '여행내용';
    
    COMMENT ON COLUMN "TRIP_PLAN"."DATE" IS '게시글작성일';
    
    COMMENT ON COLUMN "TRIP_PLAN"."COUNTRY" IS '여행국가';
    
    COMMENT ON COLUMN "TRIP_PLAN"."CITY" IS '여행도시';
    
    COMMENT ON COLUMN "TRIP_PLAN"."START_DATE" IS '여행출발일';
    
    COMMENT ON COLUMN "TRIP_PLAN"."END_DATE" IS '여행도착일';
    
    COMMENT ON COLUMN "TRIP_PLAN"."STATUS" IS '게시글 존재여부';
    
    CREATE TABLE "SHARE_BOARD" (
        "SBNUM"	NUMBER		NOT NULL,
        "TITLE"	VARCHAR2(50)		NOT NULL,
        "SNUM"	NUMBER		NOT NULL,
        "MID"	VARCHAR2(30)		NOT NULL,
        "DATE"	DATE		NOT NULL,
        "CONTENT"	VARCHAR2(4000)		NULL,
        "STNUM"	NUMBER		NOT NULL,
        "STATUS"	CHAR		NOT NULL
    );
    
    COMMENT ON COLUMN "SHARE_BOARD"."SBNUM" IS '게시글 번호';
    
    COMMENT ON COLUMN "SHARE_BOARD"."TITLE" IS '게시글 제목';
    
    COMMENT ON COLUMN "SHARE_BOARD"."SNUM" IS '물품 종류에 대한 번호';
    
    COMMENT ON COLUMN "SHARE_BOARD"."MID" IS '작성자';
    
    COMMENT ON COLUMN "SHARE_BOARD"."DATE" IS '작성날짜';
    
    COMMENT ON COLUMN "SHARE_BOARD"."CONTENT" IS '내용';
    
    COMMENT ON COLUMN "SHARE_BOARD"."STNUM" IS '거래 상태에 대한 번호';
    
    COMMENT ON COLUMN "SHARE_BOARD"."STATUS" IS '게시글이 삭제되었는지';
    
    CREATE TABLE "GUIDE_BOARD" (
        "GBNUM"	NUMBER		NOT NULL,
        "TITLE"	VARCHAR2(50)		NOT NULL,
        "MID"	VARCHAR2(30)		NOT NULL,
        "PRICE"	NUMBER		NOT NULL,
        "CONTENT"	VARCHAR2(4000)		NOT NULL,
        "DATE"	DATE		NOT NULL,
        "COUNTRY"	VARCHAR2(30)		NOT NULL,
        "CITY"	VARCHAR2(30)		NOT NULL,
        "START_DATE"	DATE		NULL,
        "END_DATE"	DATE		NULL,
        "STATUS"	CHAR		NOT NULL
    );
    
    COMMENT ON COLUMN "GUIDE_BOARD"."GBNUM" IS '게시글번호';
    
    COMMENT ON COLUMN "GUIDE_BOARD"."TITLE" IS '게시글제목';
    
    COMMENT ON COLUMN "GUIDE_BOARD"."MID" IS '게시글작성자';
    
    COMMENT ON COLUMN "GUIDE_BOARD"."PRICE" IS '여행가이드비용';
    
    COMMENT ON COLUMN "GUIDE_BOARD"."CONTENT" IS '게시글본문';
    
    COMMENT ON COLUMN "GUIDE_BOARD"."DATE" IS '게시글작성날짜';
    
    COMMENT ON COLUMN "GUIDE_BOARD"."COUNTRY" IS '가이드 할 국가명';
    
    COMMENT ON COLUMN "GUIDE_BOARD"."CITY" IS '가이드 할 도시명';
    
    COMMENT ON COLUMN "GUIDE_BOARD"."START_DATE" IS '가이드 시작일';
    
    COMMENT ON COLUMN "GUIDE_BOARD"."END_DATE" IS '가이드 종료일';
    
    COMMENT ON COLUMN "GUIDE_BOARD"."STATUS" IS '게시글 존재여부';
    
    CREATE TABLE "RPT_REASON" (
        "RSNUM"	NUMBER		NOT NULL,
        "TITLE"	VARCHAR2(30)		NOT NULL
    );
    
    COMMENT ON COLUMN "RPT_REASON"."RSNUM" IS '신고사유항목에 대한 번호';
    
    COMMENT ON COLUMN "RPT_REASON"."TITLE" IS '신고사유항목명';
    
    CREATE TABLE "FOLLOW" (
        "MID"	VARCHAR2(30)		NOT NULL
    );
    
    COMMENT ON COLUMN "FOLLOW"."MID" IS '회원아이디';
    
    CREATE TABLE "SHARE_KIND" (
        "SNUM"	NUMBER		NOT NULL,
        "SNAME"	VARCHAR2(30)		NOT NULL
    );
    
    COMMENT ON COLUMN "SHARE_KIND"."SNUM" IS '물품 종류에 대한 번호';
    
    COMMENT ON COLUMN "SHARE_KIND"."SNAME" IS '물품 종류 이름';
    
    CREATE TABLE "FOLLOWING" (
        "FID"	VARCHAR2(30)		NOT NULL,
        "MID"	VARCHAR2(30)		NOT NULL
    );
    
    COMMENT ON COLUMN "FOLLOWING"."FID" IS '팔로워 아이디';
    
    COMMENT ON COLUMN "FOLLOWING"."MID" IS '회원 아이디';
    
    CREATE TABLE "DEAL_STATE" (
        "STNUM"	NUMBER		NOT NULL,
        "STNAME"	VARCHAR2(30)		NOT NULL
    );
    
    COMMENT ON COLUMN "DEAL_STATE"."STNUM" IS '거래 상태에 대한 번호';
    
    COMMENT ON COLUMN "DEAL_STATE"."STNAME" IS '거래 상태에 대한 이름';
    
    CREATE TABLE "SHARE_ATTACHMENT" (
        "FID"	NUMBER		NOT NULL,
        "ORIGIN_NAME"	VARCHAR2(255)		NOT NULL,
        "CHANGE_NAME"	VARCHAR2(255)		NOT NULL,
        "FILE_PATH"	VARCHAR2(1000)		NOT NULL,
        "UPLOAD_DATE"	DATE		NULL,
        "FILE_LEVEL"	NUMBER		NULL,
        "DOWNLOAD_COUNT"	NUMBER		NULL,
        "STATUS"	CHAR		NULL,
        "SBNUM"	NUMBER		NOT NULL
    );
    
    COMMENT ON COLUMN "SHARE_ATTACHMENT"."SBNUM" IS '게시글 번호';
    
    CREATE TABLE "MEMBER_ATTACHMENT" (
        "FID"	NUMBER		NOT NULL,
        "MID"	VARCHAR2(30)		NOT NULL,
        "ORIGIN_NAME"	VARCHAR2(255)		NOT NULL,
        "CHANGE_NAME"	VARCHAR2(255)		NOT NULL,
        "FILE_PATH"	VARCHAR2(1000)		NOT NULL,
        "UPLOAD_DATE"	DATE		NULL,
        "DOWNLOAD_COUNT"	NUMBER		NULL,
        "STATUS"	CHAR		NULL
    );
    
    COMMENT ON COLUMN "MEMBER_ATTACHMENT"."MID" IS '회원아이디';
    
    CREATE TABLE "REVIEW_ATTACHMENT" (
        "FID"	NUMBER		NOT NULL,
        "RNUM"	NUMBER		NOT NULL,
        "ORIGIN_NAME"	VARCHAR2(255)		NOT NULL,
        "CHANGE_NAME"	VARCHAR2(255)		NOT NULL,
        "FILE_PATH"	VARCHAR2(1000)		NOT NULL,
        "UPLOAD_DATE"	DATE		NULL,
        "DOWNLOAD_COUNT"	NUMBER		NULL,
        "STATUS"	CHAR		NULL
    );
    
    COMMENT ON COLUMN "REVIEW_ATTACHMENT"."RNUM" IS '게시글번호';
    
    ALTER TABLE "BUDDY" ADD CONSTRAINT "FK_BUDDY_BOARD_TO_BUDDY_1" FOREIGN KEY (
        "BNUM"
    )
    REFERENCES "BUDDY_BOARD" (
        "BNUM"
    );
    
    ALTER TABLE "PART_BUDDY" ADD CONSTRAINT "FK_BUDDY_TO_PART_BUDDY_1" FOREIGN KEY (
        "MID"
    )
    REFERENCES "BUDDY" (
        "MID"
    );
    
    ALTER TABLE "PART_BUDDY" ADD CONSTRAINT "FK_BUDDY_TO_PART_BUDDY_2" FOREIGN KEY (
        "BID"
    )
    REFERENCES "BUDDY" (
        "BID"
    );
    
    ALTER TABLE "PART_BUDDY" ADD CONSTRAINT "FK_BUDDY_TO_PART_BUDDY_3" FOREIGN KEY (
        "BNUM"
    )
    REFERENCES "BUDDY" (
        "BNUM"
    );
    
    ALTER TABLE "FOLLOW" ADD CONSTRAINT "FK_MEMBER_TO_FOLLOW_1" FOREIGN KEY (
        "MID"
    )
    REFERENCES "MEMBER" (
        "MID"
    );
    
    ALTER TABLE "FOLLOWING" ADD CONSTRAINT "FK_MEMBER_TO_FOLLOWING_1" FOREIGN KEY (
        "FID"
    )
    REFERENCES "MEMBER" (
        "MID"
    );
    
    ALTER TABLE "FOLLOWING" ADD CONSTRAINT "FK_FOLLOW_TO_FOLLOWING_1" FOREIGN KEY (
        "MID"
    )
    REFERENCES "FOLLOW" (
        "MID"
    );
    
    

    CREATE TABLE "SREPLY" (
        "RID"           NUMBER          NOT NULL,
        "SBNUM"         NUMBER          NOT NULL,
        "RCONTENT"      VARCHAR2(400)   NOT NULL,
        "REF_GID"       NUMBER          NOT NULL,
        "MID"           VARCHAR2(30)    NOT NULL,
        "CREATE_DATE"   DATE            NOT NULL,
        "STATUS"        VARCHAR2(1)     NOT NULL);
    
    COMMENT ON COLUMN "GREPLY"."GRID"        IS '댓글번호' ;
    COMMENT ON COLUMN "GREPLY"."GRCONTENT"   IS '댓글내용' ;
    COMMENT ON COLUMN "GREPLY"."REF_GID"     IS '게시글번호' ;
    COMMENT ON COLUMN "GREPLY"."MID"         IS '작성자' ;
    COMMENT ON COLUMN "GREPLY"."CREATE_DATE" IS '작성일' ;
    COMMENT ON COLUMN "GREPLY"."STATUS"      IS '댓글존재여부' ;
    
    ALTER TABLE "GREPLY" ADD CONSTRAINT "PK_GREPLY" PRIMARY KEY ("GRID") ;
    
    ALTER TABLE "GREPLY" ADD CONSTRAINT "FK_G_BOARD_TO_GREPLY_1" FOREIGN KEY (
       "REF_GID"
    )
    REFERENCES "G_BOARD" (
       "GBNUM"
    );
    
    ALTER TABLE "GREPLY" ADD CONSTRAINT "FK_MEMBER_TO_GREPLY_1" FOREIGN KEY (
       "MID"
    )
    REFERENCES "MEMBER" (
       "MID"
    );
    
    GRANT CREATE VIEW TO SEMI_TOTO;

    CREATE OR REPLACE VIEW GLIST
    AS SELECT RNUM, GBNUM, TITLE, CONTENT, NICK, COUNTRY, CITY, START_DATE, END_DATE, PRICE, CREATE_DATE, KIND, KAKAO, GCOUNT
       FROM (SELECT ROWNUM RNUM, GBNUM, TITLE, CONTENT, NICK, COUNTRY, CITY, START_DATE, END_DATE, PRICE, CREATE_DATE, KIND, KAKAO, GCOUNT
             FROM (SELECT G.GBNUM, G.TITLE, G.CONTENT, M.NICK, G.COUNTRY, G.CITY, G.START_DATE, G.END_DATE, G.PRICE, G.CREATE_DATE, G.KIND, G.KAKAO, G.GCOUNT
                   FROM G_BOARD G JOIN MEMBER M USING(MID)
                   WHERE G.STATUS='Y'
                   ORDER BY GBNUM DESC)) ;
                   
    CREATE OR REPLACE FORCE VIEW "SEMI_TOTO"."SLIST" ("RNUM", "SBNUM", "TITLE", "CATEGORY", "WRITER", "CREATE_DATE", "CONTENT", "STNAME", "STATUS", "SCOUNT", "KAKAO", "KIND", "COUNTRY", "CITY") AS 
    SELECT RNUM, SBNUM, TITLE, CATEGORY, WRITER, CREATE_DATE, CONTENT, STNAME, STATUS, SCOUNT, KAKAO, KIND, COUNTRY, CITY
    FROM (SELECT ROWNUM RNUM, SBNUM, TITLE, SNAME CATEGORY, NICK WRITER, CREATE_DATE, CONTENT, STNAME, STATUS, SCOUNT, KAKAO, KIND, COUNTRY, CITY
          FROM (SELECT S.SBNUM, S.TITLE, K.SNAME, M.NICK, S.CREATE_DATE, S.CONTENT, T.STNAME, S.STATUS, S.SCOUNT, S.KAKAO, S.KIND, S.COUNTRY, S.CITY
                FROM S_BOARD S
                    JOIN S_KIND  K USING(SNUM)
                    JOIN S_STATE T USING(STNUM)
                    JOIN MEMBER  M USING(MID)
                WHERE S.STATUS = 'Y'
                ORDER BY S.SBNUM DESC)) ;

    COMMIT;
    
    CREATE SEQUENCE  "SEMI_TOTO"."SEQ_SFID"  MINVALUE 1 MAXVALUE 1000 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  CYCLE ;